# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_HBP) += synaptics_tcm_hbp.o

synaptics_tcm_hbp-y := \
	syna_tcm_hbp.o \
	synaptics_touchcom_core_v1.o \
	synaptics_touchcom_core_v2.o \
	synaptics_touchcom_func_base.o \
	synaptics_touchcom_func_touch.o
